version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
              fingerprints:
                - "8b:3c:ce:ed:1e:b5:67:c2:ff:dd:1d:90:38:4d:19:8d"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o "StrictHostKeyChecking=no" $DROPLET_USER@$DROPLET_IP "cd ../../var/www/chahtup.mmrdevs.com/ && git pull origin master && npm install && pm2 restart 1;"
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
